//! Layer 00: Lean 4 Formal Proof AST Transpiler

/// Individual logical inference step in Lean 4 formal language.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeanStep {
    /// Step identifier or label.
    pub label: String,
    /// Mathematical transformation description.
    pub description: String,
    /// Lean 4 tactic expression (e.g., `ring`, `linarith`, `simp`).
    pub tactic: String,
}

/// Formal mathematical theorem declaration for Lean 4 Mathlib export.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeanTheorem {
    /// Theorem name in camelCase.
    pub name: String,
    /// List of hypothesis types.
    pub hypotheses: Vec<(String, String)>,
    /// Target conclusion type expression.
    pub conclusion: String,
    /// Sequence of valid tactics proving the conclusion.
    pub steps: Vec<LeanStep>,
}

impl LeanTheorem {
    /// Create a new theorem specification.
    pub fn new(name: impl Into<String>, conclusion: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            hypotheses: Vec::new(),
            conclusion: conclusion.into(),
            steps: Vec::new(),
        }
    }

    /// Add a hypothesis variable: `name : type`.
    pub fn with_hypothesis(
        mut self,
        var_name: impl Into<String>,
        var_type: impl Into<String>,
    ) -> Self {
        self.hypotheses.push((var_name.into(), var_type.into()));
        self
    }

    /// Append a formal verification tactic step.
    pub fn with_step(
        mut self,
        label: impl Into<String>,
        desc: impl Into<String>,
        tactic: impl Into<String>,
    ) -> Self {
        self.steps.push(LeanStep {
            label: label.into(),
            description: desc.into(),
            tactic: tactic.into(),
        });
        self
    }

    /// Render into syntactically valid Lean 4 source code.
    pub fn to_lean_code(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("theorem {} ", self.name));

        for (var, typ) in &self.hypotheses {
            out.push_str(&format!("({} : {}) ", var, typ));
        }

        out.push_str(&format!(": {} := by\n", self.conclusion));

        if self.steps.is_empty() {
            out.push_str("  rfl\n");
        } else {
            for step in &self.steps {
                out.push_str(&format!("  -- {}: {}\n", step.label, step.description));
                out.push_str(&format!("  {}\n", step.tactic));
            }
        }
        out
    }
}

/// Complete verifiable Lean 4 proof-certificate file representation.
#[derive(Debug, Clone)]
pub struct LeanProofCertificate {
    /// Module name.
    pub module_name: String,
    /// Collection of verified theorems.
    pub theorems: Vec<LeanTheorem>,
}

impl LeanProofCertificate {
    /// Create an empty proof certificate.
    pub fn new(module_name: impl Into<String>) -> Self {
        Self {
            module_name: module_name.into(),
            theorems: Vec::new(),
        }
    }

    /// Add a theorem to the certificate.
    pub fn add_theorem(&mut self, theorem: LeanTheorem) {
        self.theorems.push(theorem);
    }

    /// Render complete `.lean` export.
    pub fn render_lean_file(&self) -> String {
        let mut file = String::new();
        file.push_str(&format!(
            "-- Verified Formal Proof Certificate: {}\n",
            self.module_name
        ));
        file.push_str("-- Generated by SC-Substrate Sovereign Core Layer 00\n");
        file.push_str("import Mathlib.Data.Real.Basic\n");
        file.push_str("import Mathlib.Tactic.Ring\n\n");

        for thm in &self.theorems {
            file.push_str(&thm.to_lean_code());
            file.push('\n');
        }
        file
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lean4_theorem_rendering() {
        let thm = LeanTheorem::new("ball_addition_comm", "a + b = b + a")
            .with_hypothesis("a", "Real")
            .with_hypothesis("b", "Real")
            .with_step("Step1", "Apply ring identity", "ring");

        let code = thm.to_lean_code();
        assert!(
            code.contains("theorem ball_addition_comm (a : Real) (b : Real) : a + b = b + a := by")
        );
        assert!(code.contains("ring"));
    }
}
